default:
  max_lines : 3
  max_bet : 5
  min_bet : 1

  rows : 3
  cols : 3

  symbol_count : {
      "A":2,
      "B":4,
      "C":6,
      "D":8,
  }
  symbol_value : {
      "A":8,
      "B":3,
      "C":2,
      "D":2,
  }